### ISSUE TITLE
Requesting permission to make trailer

### ISSUE THREAD

**Issue by SusDTSteve** [cubosphere/cubosphere-code#55]
I would like to create a trailer for "Cubosphere" beta 0.04a,

**Additional context**
All I need is some sort of release date, and permission to use stuff as in game-play E.C.T
(Also I'm quite patient so don't test how patient I am, most likely you will run out of patience yourself.)

**Comment by v1993** [comment]
There is no actual ongoing development, really, so no release date either (unless someone else decides to resume work on this). So, are you patient enough to wait for eternity (well, I'd run out of patience before that)? Because Cubosphere beta 0.04a probably won't land any time before Half-Life 3 does.

On the other hand, ground-up rewrite is well possible, but that is a different story, also lacking any sort of release date, at least right now.

You have my permission to use any in-game stuff and such as far as my right to give any sort of such permission goes. You wouldn't need it tho, GPL3 have you covered. Just note that game data (music/textures) almost surely have licensing issues and it's not like I can do much about it.
